plugins:
  - jekyll-avatar
  - jekyll-feed
  - jekyll-mentions
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji

domain: maemon4095.github.io
url: https://maemon4095.github.io
baseurl: /HackNoSense

kramdown:
  syntax_highlighter_opts:
    default_lang: plaintext

sass:
  sass_dir: assets/sass
  style: expanded

strict_front_matter: true

collections:
  posts:
    permalink: "/:collection/:year/:month/:day/:title:output_ext"
    output: true
  categories:
    directory: pages/categories
    output: true

defaults:
  - scope:
      path: _posts
      type: posts
    values:
      layout: post