plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

domain: maemon4095.github.io
url: https://maemon4095.github.io
baseurl: /Hack-a-Sense

kramdown:
  parse_block_html: true
  highlighter: none
  syntax_highlighter_opts:
    disable: true

sass:
  sass_dir: assets/sass
  style: expanded

strict_front_matter: true

collections:
  posts:
    permalink: "/:collection/:year/:month/:day/:title:output_ext"
    output: true
  categories:
    directory: pages/categories
    output: true

defaults:
  - scope:
      path: _posts
      type: posts
    values:
      layout: post