name: build

on:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    env:
      framework: 'net5.0'
      config: 'Release'
    steps:
    - name: initialize variables
      run: echo "repo=$(echo ${{ github.repository }} | sed -e 's|.*/||g')" >> $GITHUB_ENV
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - run: dotnet publich -c $config -f $framework
    - uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./${{env.repo}}/bin/${{env.config}}/${{env.framework}}/publish/wwwroot
        publish_branch: pages
        enable_jekyll: false

    
