name: build

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: copy to pages
        env: 
          SRC_DIR: 'root'
          DST_BRANCH: 'pages'
        run: |
          files=$(find $SRC_DIR -type f)
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git fetch
          git switch $DST_BRANCH
          git rm -rf *
          git restore --source ${GITHUB_REF##*/} $files
          git add -A
          git commit -m "copy from main"
          git push origin $DST_BRANCH
