name: build

on:
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: copy to pages
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git fetch
          git switch pages
          git rm -rf *
          git restore --source ${GITHUB_REF##*/} site
          mv site/* .
          git add -A
          git commit -m "copy from main"
          git push
