name: build

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: copy to pages
        env: 
          SRC_DIR: 'root'
          DST_BRANCH: 'pages'
        run: |
          echo ${GITHUB_REF##*/} 
          git branch -a
          git checkout $DST_BRANCH
          git rm -rf *
          git restore --source ${GITHUB_REF##*/} $SRC_DIR
