name: build

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    name: copy to pages
    uses: actions/checkout@v3
    with:
      ref: pages
      path: articles

